### PR TITLE
feat(Context-Based Restrictions): add service group support to Operations

### PR DESCRIPTION
**Pull request by JonahFarc**
## PR summary
Adds service group support to operations

## PR Checklist
Please make sure that your PR fulfills the following requirements:  
- [X] The commit message follows the [Angular Commit Message Guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-commit-message-guidelines).
- [X] Tests for the changes have been added (for bug fixes / features)
- [X] Docs have been added / updated (for bug fixes / features)

## Current vs new behavior  
service_name parameter can now be replaced with the service group parameter.

## Does this PR introduce a breaking change?    
- [ ] Yes
- [X] No

### CODE REVIEW

**Review by padamstx — COMMENTED** [review]
LGTM.  Please post evidence (screenshot, etc.) of the integration tests and examples runnng clean.

**Comment by JonahFarc** [comment]
Successful test runs
image

**Comment by JonahFarc** [comment]
Continuation of examples run 
image

**Review by padamstx — APPROVED** [review]
LGTM

**Pull request merged**
