### PR TITLE
add latest Context-based Restrictions features

### PR DESCRIPTION
**Pull request by soohoowoohoo**
## PR summary

Add ability to query by rule enforcement modes (previously released) and add features needed for Context-based Restrictions rule API types.

- feat(Context-based Restrictions): add enforcement_mode query param
- feat(Context-based Restrictions): add service ref address location support
- feat(Context-based Restrictions): add rule API type support

## PR Checklist
Please make sure that your PR fulfills the following requirements:  
- [x] The commit message follows the [Angular Commit Message Guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-commit-message-guidelines).
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## Does this PR introduce a breaking change?    
- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by soohoowoohoo** [comment]
@padamstx @dpopp07 the travis job is showing as canceled due to insufficient credits. Will this be a problem for getting this PR merged when ready? (I assume the answer applies to all language SDKs.)

**Review by padamstx — CHANGES_REQUESTED** [review]
Need an update to the integration tests to exercise the new operation.  Also, if there are any other additions (parameters, properties, etc.) to the API where it would make sense to exercise them in the int tests and examples, let's go ahead and make those changes as part of this PR.

**Review by padamstx — APPROVED** [review]
LGTM

**Pull request merged**
