### PR TITLE
feat(Partner Usage Reports): add new service to project

### PR DESCRIPTION
**Pull request by manukm-ibm**
## PR summary

Adding new partner API to fetch resource usage reports.
TRI: https://github.ibm.com/BSS/architecture/blob/master/design-docs/cosell/partner.md
Issue: https://github.ibm.com/BSS/metering-deliverables/issues/2063

## PR Checklist
Please make sure that your PR fulfills the following requirements:  
- [x] The commit message follows the [Angular Commit Message Guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-commit-message-guidelines).
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## Does this PR introduce a breaking change?    
- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by manukm-ibm** [comment]
Integration test results
Screenshot 2024-01-23 at 11 30 54 AM

Example test results
Screenshot 2024-01-23 at 11 31 17 AM

**Review by padamstx — APPROVED** [review]
LGTM

**Review by padamstx — APPROVED** [review]
LGTM

**Pull request merged**
