### PR TITLE
fix(Usage Reports): re-gen service after recent API changes

### PR DESCRIPTION
**Pull request by Jdatechong**
## PR summary
Regeneration of the usage reports service. Mainly intended to add `catalog_id` to `instance_usage` and `resource`.

## PR Checklist
Please make sure that your PR fulfills the following requirements:  
- [x] The commit message follows the [Angular Commit Message Guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-commit-message-guidelines).
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## Does this PR introduce a breaking change?    
- [ ] Yes
- [x] No

## Other information

Test results:
```
Running Suite: UsageReportsV4 Suite
===================================
Random Seed: 1712872455
Will run 109 of 109 specs

•••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••
Ran 109 of 109 Specs in 3.467 seconds
SUCCESS! -- 109 Passed | 0 Failed | 0 Pending | 0 Skipped
PASS
ok      github.com/IBM/platform-services-go-sdk/usagereportsv4  3.842s
```
Integration tests:
```
Running Suite: UsageReportsV4 Suite
===================================
Random Seed: 1712794296
Will run 120 of 120 specs

••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••
Ran 120 of 120 Specs in 16.652 seconds
SUCCESS! -- 120 Passed | 0 Failed | 0 Pending | 0 Skipped
PASS
ok      github.com/IBM/platform-services-go-sdk/usagereportsv4  16.979s
```
Examples:
```
Ran 124 of 124 Specs in 19.398 seconds
SUCCESS! -- 124 Passed | 0 Failed | 0 Pending | 0 Skipped
PASS
ok      github.com/IBM/platform-services-go-sdk/usagereportsv4  20.178s
```

### CODE REVIEW

**Comment by padamstx** [comment]
@jdatechong it looks like you used a fairly old version of the SDK generator (3.75.0) to regen this service.  Please install the latest version of the generator (currently 3.89.0) and regen with that.

**Comment by padamstx** [comment]
@Jdatechong just wanted to double-check that you saw my comment above about needing to re-gen the go and java sdk code with a recent version of the SDK generator.  I've merged the node and python PRs so as of right now, your service is not in sync between go/java vs node/python.

**Comment by Jdatechong** [comment]
@padamstx the go and java sdks have been regenerated with a newer version of the sdk generator

test results after update:
```
Running Suite: UsageReportsV4 Suite
===================================
Random Seed: 1713384902
Will run 103 of 103 specs

•••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••
Ran 103 of 103 Specs in 3.166 seconds
SUCCESS! -- 103 Passed | 0 Failed | 0 Pending | 0 Skipped
PASS
ok      github.com/IBM/platform-services-go-sdk/usagereportsv4  3.532s
```

**Review by padamstx — APPROVED** [review]
LGTM

**Pull request merged**
