### PR TITLE
feat(Activity Tracker): add new atracker v2 service to project

### PR DESCRIPTION
**Pull request by johnymathew**
## PR summary
SDK for Atracker services v2 API pushing into atrackerv2 folder. There is a v1 version available in atrackerv1 folder

## PR Checklist
Please make sure that your PR fulfills the following requirements:  
- [x] The commit message follows the [Angular Commit Message Guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-commit-message-guidelines).
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features) https://test.cloud.ibm.com/apidocs/atracker/atracker-v2

## Does this PR introduce a breaking change?    
- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by johnymathew** [comment]
Screen Shot 2022-03-16 at 6 36 01 PM

**Review by padamstx — APPROVED** [review]
LGTM

**Review by padamstx — CHANGES_REQUESTED** [review]
Oops, I approved, but then realized we need to update the README.md file as well.

**Review by padamstx — CHANGES_REQUESTED** [review]
Changes look good, but we still need to update the README.md file to include the new service :)

**Pull request merged**
