### PR TITLE
Regen atracker 07152022

### PR DESCRIPTION
**Pull request by yingwang-us**
Signed-off-by: yingwang_us [bluewang@yahoo.com](mailto:bluewang@yahoo.com)

## PR Checklist
Please make sure that your PR fulfills the following requirements:  
- [x] The commit message follows the [Angular Commit Message Guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-commit-message-guidelines).
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## Does this PR introduce a breaking change?    
- [ ] Yes
- [x] No

## Other information

- [x] remove optional `region` parameter from List route call since v2 route is global
- [x] An additional `metadata_region_backup` property is added for [atracker v2 setting api](https://cloud.ibm.com/apidocs/atracker-v2#get-settings). Therefore update the SDK accordingly.

### CODE REVIEW

**Comment by padamstx** [comment]
@yingwang-us Could you please amend your commits (perhaps by using `git rebase -i`) to include the sign-off (i.e. it's the -s option on commit, or you can just add the "sign off" message to the body of your commit messages.
For some reason, github.com is now requiring commits to be signed-off.

**Review by padamstx — APPROVED** [review]
LGTM

**Comment by yingwang-us** [comment]
thanks Phil, I will do it next time.

**Pull request merged**
