### PR TITLE
feat(Enterprise Billing Units): add start and limit parameters to billing unit APIs

### PR DESCRIPTION
**Pull request by Jdatechong**
## PR summary

Adds start and limit parameters to support pagination for certain Enterprise Billing Units APIs

## PR Checklist
Please make sure that your PR fulfills the following requirements:  
- [x] The commit message follows the [Angular Commit Message Guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-commit-message-guidelines).
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## Current vs new behavior  

Results can now be optionally paginated using the start and limit parameters.

## Does this PR introduce a breaking change?    
- [ ] Yes
- [x] No

## Test results
```
Ran 56 of 64 Specs in 1.330 seconds
SUCCESS! -- 56 Passed | 0 Failed | 0 Pending | 8 Skipped
PASS
ok      github.com/IBM/platform-services-go-sdk/enterprisebillingunitsv1        1.709s
```

### CODE REVIEW

**Review by padamstx — CHANGES_REQUESTED** [review]
I've done a quick preliminary review of the PR and what you've done so far looks good, but we also would need the examples and integration tests to be updated to reflect the use of the new Pager structs.
Especially the examples since we want to encourage users to use the Pagers.  The Enterprise Usage Reports service might be a good one to use as a model for updating the examples and int tests.

**Review by padamstx — APPROVED** [review]
LGTM,
please paste a screenshot of a successful run of the integration tests and examples:
```
cd enterprisebillingunitsv1
go test -tags=integration
go test -tags=examples
```

**Comment by padamstx** [comment]
@Jdatechong Looks like the build for this PR also had lint errors. You can run `make lint` in the project root to run the linter on the code.  After fixing the issues, just commit and push to your branch.

**Comment by Jdatechong** [comment]
Results from `go test -tags=integration`
```
••••••••••••••••••••••••••••••••••••••••••••••••••••••••
Ran 56 of 66 Specs in 1.168 seconds
SUCCESS! -- 56 Passed | 0 Failed | 0 Pending | 10 Skipped
PASS
ok      github.com/IBM/platform-services-go-sdk/enterprisebillingunitsv1        1.998s
```
Results from `go test -tags=examples`
```
Ran 56 of 62 Specs in 1.179 seconds
SUCCESS! -- 56 Passed | 0 Failed | 0 Pending | 6 Skipped
PASS
ok      github.com/IBM/platform-services-go-sdk/enterprisebillingunitsv1        1.456s
```

**Comment by padamstx** [comment]
My guess is that the 10 int tests and 6 examples that were skipped are due to a missing config file for your service (i.e. enterprise_billing_units.env).  You can find this in the examples file:
```
//
// This file provides an example of how to use the Enterprise Billing Units service.
//
// The following configuration properties are assumed to be defined:
//
// ENTERPRISE_BILLING_UNITS_URL=<service url>
// ENTERPRISE_BILLING_UNITS_AUTHTYPE=iam
// ENTERPRISE_BILLING_UNITS_APIKEY=<your iam apikey>
// ENTERPRISE_BILLING_UNITS_AUTH_URL=<IAM token service URL - omit this if using the production environment>
// ENTERPRISE_BILLING_UNITS_ENTERPRISE_ID=<id of enterprise to use for examples>
// ENTERPRISE_BILLING_UNITS_BILLING_UNIT_ID=<id of billing unit to use for examples>
```

**Comment by Jdatechong** [comment]
Results from the integration tests:
```
Ran 60 of 60 Specs in 36.241 seconds
SUCCESS! -- 60 Passed | 0 Failed | 0 Pending | 0 Skipped
PASS
ok      github.com/IBM/platform-services-go-sdk/enterprisebillingunitsv1        37.562s
```
Results from the examples:
```
Ran 57 of 57 Specs in 8.205 seconds
SUCCESS! -- 57 Passed | 0 Failed | 0 Pending | 0 Skipped
PASS
ok      github.com/IBM/platform-services-go-sdk/enterprisebillingunitsv1        9.537s
```

**Pull request merged**
