### PR TITLE
fix(Catalog Management): Re-gen SDK

### PR DESCRIPTION
**Pull request by dubee**
## PR summary

Re-gen of the Catalog Management SDK to get the latest API updates.

## PR Checklist
Please make sure that your PR fulfills the following requirements:  
- [x] The commit message follows the [Angular Commit Message Guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-commit-message-guidelines).
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## Does this PR introduce a breaking change?    
- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by dubee** [comment]
Test results:
Screen Shot 2022-09-14 at 2 30 02 PM

**Review by padamstx — COMMENTED** [review]
Did you really intend to delete the integration tests and examples?

**Comment by dubee** [comment]
> Did you really intend to delete the integration tests and examples?

I didn't intend to delete the examples. The other integration tests files are old though, so I thought we could delete those.

**Comment by padamstx** [comment]
> > Did you really intend to delete the integration tests and examples?
> I didn't intend to delete the examples. The other integration tests files are old though, so I thought we could delete those.

I'm ok with you deleting the old int test files as long as the new file contains a set of integration tests that exercise each operation of the service.   Re: the working examples, those need to be put back in place as well.

I skimmed through the new integration test file and there are a LOT of test values being used for properties that are not "real", such as "testString", etc.   These mock values are being used by the generator because the API definition lacks sufficient "example" values for request bodies, responses, schemas, and parameters.
It's a best practice to populate the API definition with realistic examples along with any links that are needed to define the inter-operation relationships (e.g. an "id" property from the "create catalog" response might be needed to invoke the "get catalog" operation).
With these additions to the API definition, the generated examples and int tests will be closer to "ideal", plus those same example values will be used across the different languages, which is example what we want when we use the working example code fragments in the online API Reference docs.

**Review by padamstx — APPROVED** [review]
Changes look good.

Please post a screenshot of a clean run of the int tests and examples.
i.e. `cd catalogmanagementv1` then `go test -tags=integration,examples`.
Once we have that I can merge.

**Comment by dubee** [comment]
@padamstx, I forced pushed updates. Several links were added to the Swagger. 

Screen Shot 2022-09-20 at 5 24 27 PM

**Comment by padamstx** [comment]
@dubee FYI, the pull request build failed due to some compile errors in the examples code.  Did you run those locally?  (e.g. `cd catalogmanagementv1`, `go test -tags=examples`)
My guess is that the compile errors are due to changes in the generated service code that resulted from your re-gen.

**Comment by dubee** [comment]
@padamstx, I've updated the examples to compile and run. 

Here's the output from `go test -tags=integration,examples`: 
Screen Shot 2022-09-21 at 12 43 39 PM

**Pull request merged**
