### PR TITLE
feat(Context-Based Restrictions): add Service Ref Target

### PR DESCRIPTION
**Pull request by JonahFarc**
## PR summary
Add support for new endpoint
Update examples to match the API

## PR Checklist
Please make sure that your PR fulfills the following requirements:  
- [X] The commit message follows the [Angular Commit Message Guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-commit-message-guidelines).
- [X] Tests for the changes have been added (for bug fixes / features)
- [X] Docs have been added / updated (for bug fixes / features)

## Current vs new behavior  
Adds new endpoint for singular service ref target

## Does this PR introduce a breaking change?    
- [ ] Yes
- [X] No

### CODE REVIEW

**Review by soohoowoohoo — APPROVED** [review]

**Comment by JonahFarc** [comment]
@padamstx this is good to be merged

**Review by padamstx — APPROVED** [review]
LGTM

**Comment by JonahFarc** [comment]
Integration Test Output:
image

Examples Output:
image

**Pull request merged**
