### PR TITLE
fix(Global Search & Tagging): re-gen services with latest API definition

### PR DESCRIPTION
**Pull request by fabrizio-leoni**
## PR summary

Removed all references to transdaction-id

## PR Checklist
Please make sure that your PR fulfills the following requirements:  
- [x] The commit message follows the [Angular Commit Message Guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-commit-message-guidelines).
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## Does this PR introduce a breaking change?    
- [x] Yes
- [ ] No

### CODE REVIEW

**Comment by fabrizio-leoni** [comment]
image

**Comment by fabrizio-leoni** [comment]
image

**Review by padamstx — APPROVED** [review]
LGTM

**Pull request merged**
