### PR TITLE
fix(Metrics Router): add new region eu-fr2

### PR DESCRIPTION
**Pull request by PhaniDivi-613**
## PR summary
Added new region BNPP(eu-fr2) to metrics-router

## PR Checklist
Please make sure that your PR fulfills the following requirements:  
- [x] The commit message follows the [Angular Commit Message Guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-commit-message-guidelines).
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## Current vs new behavior  
Added new region. No change in old code

## Does this PR introduce a breaking change?    
- [ ] Yes
- [x] No

## Other information

### CODE REVIEW

**Comment by PhaniDivi-613** [comment]
Ran integration tests
image

**Review by padamstx — APPROVED** [review]
LGTM

**Review by padamstx — APPROVED** [review]
LGTM

**Pull request merged**
