### PR TITLE
fix(Metrics Router): add new region eu-es

### PR DESCRIPTION
**Pull request by adya1303**
## PR summary
Added new region Madrid(eu-es) to metrics-router

## PR Checklist
Please make sure that your PR fulfills the following requirements:  
- [x] The commit message follows the [Angular Commit Message Guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-commit-message-guidelines).
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## Current vs new behavior  
Added new region. No change in old code

## Does this PR introduce a breaking change?    
- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by padamstx** [comment]
Is this a duplicate of #281?

**Comment by adya1303** [comment]
> Is this a duplicate of #281?

No Phil. This one is for metrics-router. I changed the description for 281. That is for Atracker.

**Comment by adya1303** [comment]
Ran integration tests - 
image

**Pull request merged**
