### PR TITLE
test(Resource Controller): cleanup Resource Controller integration tests and examples

### PR DESCRIPTION
**Pull request by arshabbir**
## PR Checklist
Please make sure that your PR fulfills the following requirements:  
- [ ] The commit message follows the [Angular Commit Message Guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-commit-message-guidelines).
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## Does this PR introduce a breaking change?    
- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by padamstx** [comment]
Please follow the instructions contained in update_service.md.

**Review by padamstx — COMMENTED** [review]
It's unclear why you are removing test test/example code for certain operations.

**Comment by padamstx** [comment]
@arshabbir Hi, what are your plans for this PR? I'll convert it to a draft PR for now until we know what will be done with it.

**Comment by arshabbir** [comment]
Hi @padamstx , I am closing this PR as the changes are addressed in another PR . thank you

**Pull request closed without merging**
