### PR TITLE
fix(Activity Tracker): re-gen service after recent API changes

### PR DESCRIPTION
**Pull request by jorge-ibm**
## PR summary
This PR contains an update to the Activity Tracker service after [recent](https://github.ibm.com/mkistler/atracker/commit/cbbea2738b78e0d8a0bb72f975305e3bbb6dbceb) API changes.

## PR Checklist
Please make sure that your PR fulfills the following requirements:  
- [x] The commit message follows the [Angular Commit Message Guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-commit-message-guidelines).
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type  

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] New tests
- [x] Build/CI related changes
- [ ] Documentation content changes
- [ ] Other (please describe)

## Does this PR introduce a breaking change?    
- [ ] Yes
- [ ] No

### CODE REVIEW

**Comment by padamstx** [comment]
@jorge-ibm My usual practice for the platform services is to make sure that the generated code in the SDK is associated with the version of the API definition in the production branch of the cloud-api-docs repo (in the case of atracker, they don't yet have anything in their production branch, so test would suffice until that happens).   Let's work to get the changes from Mike's fork merged into the master branch of https://github.ibm.com/cloud-api-docs/atracker before we merge in this PR.

**Review by padamstx — APPROVED** [review]
LGTM

**Comment by jorge-ibm** [comment]
@yingwang-us can you please re-test the examples/IT and add your review to this? thanks

**Review by padamstx — APPROVED** [review]
LGTM

**Review by yingwang-us — APPROVED** [review]

**Pull request merged**
