### PR TITLE
feat(Usage Reports): add "created_by_email_id" to Offer schema

### PR DESCRIPTION
**Pull request by Jdatechong**
## PR summary

updated offers to have the CreatedByEmailID field

## PR Checklist
Please make sure that your PR fulfills the following requirements:  
- [x] The commit message follows the [Angular Commit Message Guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-commit-message-guidelines).
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## Current vs new behavior  

updated offers to have the CreatedByEmailID field

## Does this PR introduce a breaking change?    
- [ ] Yes
- [x] No

## Other information

Test results:
```
•••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••
Ran 109 of 109 Specs in 3.477 seconds
SUCCESS! -- 109 Passed | 0 Failed | 0 Pending | 0 Skipped
PASS
ok      github.com/IBM/platform-services-go-sdk/usagereportsv4  5.164s
```

### CODE REVIEW

**Comment by pyrooka** [comment]
@Jdatechong the builds are finally green, but I just noticed you used an old version of the generator for this PR (released on Apr 10). Could you re-gen your code by using the current latest, please? This applies to your other PRs too, but I'll leave comments just to make sure we won't miss anything. Thanks in advance and sorry for the late notice!

**Review by pyrooka — CHANGES_REQUESTED** [review]
@Jdatechong the builds are finally green, but I just noticed you used an old version of the generator for this PR (released on Apr 10). Could you re-gen your code by using the current latest, please? This applies to your other PRs too, but I'll leave comments just to make sure we won't miss anything. Thanks in advance and sorry for the late notice!

**Comment by Jdatechong** [comment]
@pyrooka SDK has been regenerated with version 3.96.0

**Review by pyrooka — APPROVED** [review]
Thanks for making this change, now everything looks good to me!

**Pull request merged**
