### PR TITLE
feat(Context Based Restrictions): add service to project

### PR DESCRIPTION
**Pull request by JonahFarc**
## PR summary
Added Context-Based Restrictions API

## PR Checklist
Please make sure that your PR fulfills the following requirements:  
- [X] The commit message follows the [Angular Commit Message Guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-commit-message-guidelines).
- [X] Tests for the changes have been added (for bug fixes / features)
- [X] Docs have been added / updated (for bug fixes / features)

## Current vs new behavior  
Added Context-Based Restrictions API

## Does this PR introduce a breaking change?    
- [ ] Yes
- [X] No

### CODE REVIEW

**Comment by Andras-Csanyi** [comment]
@JonahFarc Thanks for the PR! Could you please take a look at the CLA Assistant message? It seems all the 4 PR has the same issue.

**Comment by JonahFarc** [comment]
@Andras-Csanyi I've resolved the issue

**Comment by padamstx** [comment]
Before we merge this PR, can you describe what service this is?   Is the service within the "Platform Services" category in the IBM Cloud catalog?

**Comment by JonahFarc** [comment]
> Before we merge this PR, can you describe what service this is? Is the service within the "Platform Services" category in the IBM Cloud catalog?

Yeah, absolutely. This is within the Platform Services category and serves as an easily consumable access management service that provides a consistent, centralized rule management and enforcement framework for all IBM Cloud services

**Comment by padamstx** [comment]
> > Before we merge this PR, can you describe what service this is? Is the service within the "Platform Services" category in the IBM Cloud catalog?
> 
> Yeah, absolutely. This is within the Platform Services category and serves as an easily consumable access management service that provides a consistent, centralized rule management and enforcement framework for all IBM Cloud services

Thanks, I checked the staging catalog and can see the service's API reference there, but it's still not available in the prod catalog (which is what the README doc link points to).  Normally, we recommend that the production version of a service's API definition is used to generate the SDK code.  At least for some services, the API definition in the cloud-api-docs repo's test branch differs from the one in production (service URL, example values, etc.) and so it's usually best to make sure the production API def is used for code generation in the SDKs.
Do you know when the service will achieve GA?

**Comment by padamstx** [comment]
@JonahFarc Before we can merge in this PR, we'll need to add integration tests and working examples.   Note that for each of the 4 languages (go, java, node, python), the SDK generator can be used to generate an initial source file for integrations and (separately) working examples.   These generated files are then manually modified as needed to get the int tests and examples into "shape".     Please reach out to @Andras-Csanyi for any questions about this.

**Pull request closed without merging**
