### PR TITLE
 fix(Context-Based Restrictions): fix output to Operations

### PR DESCRIPTION
**Pull request by JonahFarc**
## PR summary
Add on to previous work:
https://github.com/IBM/platform-services-go-sdk/pull/277

The output is improper due to generation from an older version of the swagger. The change should be very minor and will be propagated to the other languages' PRs.

## PR Checklist
Please make sure that your PR fulfills the following requirements:  
- [X] The commit message follows the [Angular Commit Message Guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-commit-message-guidelines).
- [X] Tests for the changes have been added (for bug fixes / features)
- [X] Docs have been added / updated (for bug fixes / features)

## Current vs new behavior  
Adds the "Type" output

## Does this PR introduce a breaking change?    
- [ ] Yes
- [X] No

### CODE REVIEW

**Comment by JonahFarc** [comment]
Test screenshots: 
image

**Comment by JonahFarc** [comment]
Waiting on a review from someone on my side as well

**Review by padamstx — APPROVED** [review]
LGTM

**Review by soohoowoohoo — APPROVED** [review]
Changes look good

**Comment by JonahFarc** [comment]
Test Screenshot:
image
Examples Screenshot:
image

**Comment by JonahFarc** [comment]
@padamstx should be good to merge whenever you're ready!

**Pull request merged**
